### ISSUE TITLE
Resolving single command usage (pip, runserver)

### ISSUE THREAD

**Issue by desanctis-n** [JMalegni/DisasterPrepApp#1]
Find way to install using pip and requirements.txt, and run server with single command (e.g. python3 manage.py runserver) from any directory

**Comment by JMalegni** [comment]
Done, the test website is now accessible with these steps:
In your terminal, run "pip install SEELE-test"
Run "yourmother"
While that's running, go to your browser and paste "http://127.0.0.1:8000/" into the address bar
Profit
