### ISSUE TITLE
Map usually doesn't work the first time in the poster

### ISSUE THREAD

**Issue by Lchenicek** [JMalegni/DisasterPrepApp#18]
Not always, but sometimes the map doesn't load completely correctly when I load it for the first time in a bit. Usually, going back and reloading it will usually fix it. The API is returning correctly and the information is being passed to the front end correctly even when it doesn't look correct. I'm wondering if this may be a wifi dependence issue but I don't have much confidence in that idea.

**Comment by JMalegni** [comment]
Xael seemingly fixed this today
