### ISSUE TITLE
Delete profile page image resizing

### ISSUE THREAD

**Issue by JMalegni** [JMalegni/DisasterPrepApp#36]
The account deletion page character sprites are very large on a mobile view, requirnig the user to scroll like three times to reach the button

![image](https://github.com/user-attachments/assets/e0738fea-0ba5-4f0f-b74c-dcb79ac6eab8)

**Comment by ceejayferrer** [comment]
I kind of left this as intentional because it's pretty funny but I can fix this real quick

**Comment by ceejayferrer** [comment]
<img width="105" alt="image" src="https://github.com/user-attachments/assets/870548f8-8d6e-444f-a69c-275d66382b3c">

**Comment by ceejayferrer** [comment]
<img width="105" alt="image" src="https://github.com/user-attachments/assets/c5104049-2338-476a-8b89-4862b2fccaee">
